fix: apy chart for ryeth detail page
strangelove-ventures/sommelier pull request #1058
Opened 2023-05-15 20:55 UTC by joshuanatanielnm

Fixes #1047 

## Description

Enable and fix chat for real yield eth in detail page

## Changes

List any technical changes.

- [fix: apy chart for ryeth detail page](https://github.com/strangelove-ventures/sommelier/commit/cb1dc7b743ccd92f6e8491983301578de48860b0)

2023-05-15 21:08 UTC, codingki requested changes

2023-05-15 21:08 UTC, codingki commented on src/data/context/apyChartContext.tsx
> +  const getDecimals = sgData?.cellar?.asset.decimals ?? 18
non blocking the merge but this "get..." name is a variable not a function. Better rename this to `sgDecimals`

2023-05-15 21:08 UTC, codingki commented on src/data/context/apyChartContext.tsx
> +  const [{ data: sgData }] = useGetStrategyDataQuery({
we have `useStrateyData` please use that instead this subgraph. so it's not refetching

2023-05-15 21:08 UTC, codingki commented on src/data/context/apyChartContext.tsx
> +  const getDecimals = sgData?.cellar?.asset.decimals ?? 18
fallback value better `6` because we have only one strategy that underlying asset is eth

2023-05-15 21:22 UTC, codingki approved these changes

2023-05-16 00:32 UTC, asaadam approved these changes

2023-05-16 03:52 UTC, merged