fix: fix feedback 2-jun
strangelove-ventures/sommelier pull request #1101
Opened 2023-06-01 19:34 UTC by asaadam

Fix all feedbacks from this sheet : 

https://docs.google.com/spreadsheets/d/1hJY24OMi5Zt-z-mhOoZJItP6LTu5IhoBmTzQ8BjBoXE/edit#gid=1331233554

2023-06-01 19:49 UTC, codingki commented on src/utils/config.ts
> +    UNI: {
move this upper join it with other tokens

2023-06-01 20:08 UTC, joshuanatanielnm commented on src/components/_cards/ApyPerfomanceCard.tsx
I think this Typo

2023-06-01 20:10 UTC, joshuanatanielnm commented on src/data/actions/common/getUserDataAllStrategies.ts
remove console.log, and use console.error for error msg

2023-06-01 20:11 UTC, joshuanatanielnm requested changes
Please remove console.log, and update typo text

2023-06-02 11:14 UTC, sandbochs commented
Just finished 24hrs of traveling. Will review this in about 8 hrs.

2023-06-02 15:44 UTC, merged