remove GHO rewards
strangelove-ventures/sommelier pull request #1433
Opened 2023-11-25 09:37 UTC by henrio123

Fixes #<ISSUE_NUMBER>

## Description

Describe big picture changes here. This will give viewers context for the changes.

## Changes

List any technical changes.

- [ ] Change 1

## Screenshots (if appropriate):

## Testing Steps

As a reviewer, what steps should I take to verify this is working correctly?

- [ ] Step 1

## Links

Add links to Figma files, documentation, etc.

2023-11-25 17:25 UTC, philipjames44 requested changes

2023-11-25 17:25 UTC, philipjames44 commented on src/data/strategies/turbo-gho.ts
> +    // },
If we're going to comment these out it should be a multiline comment (/* text */)

2023-11-26 15:09 UTC, zmanian approved these changes

2023-11-26 16:35 UTC, philipjames44 approved these changes

2023-11-26 16:35 UTC, merged