chore(analytics): add bridge analytics event track
strangelove-ventures/sommelier pull request #445
Opened 2022-08-30 20:31 UTC by codingki

## Description

Add Bridge analytics event track

## Changes

- [x] [chore(analytics): add bridge analytics event track](https://github.com/strangelove-ventures/sommelier/commit/062f3623c36eded4617d14689876d29d91f63044)

2022-08-30 20:33 UTC, xanderjl approved these changes
LGTM 🚀 

I suppose this will need to be tested in mixpanel

2022-08-30 20:33 UTC, codingki commented
@sandbochs Please verify the event track key

2022-08-30 20:43 UTC, sandbochs requested changes

2022-08-31 16:46 UTC, sandbochs approved these changes
looks good, thanks for the follow up

2022-08-31 16:55 UTC, merged