Feat/588 token price second design iteration
strangelove-ventures/sommelier pull request #607
Opened 2022-11-08 21:28 UTC by joshuanatanielnm

#588 

## Description

Add 1M Change vs ETH/BTC 50/50 for token price second design iteration

## Changes

List any technical changes.

- [x] [feat: create hooks for eth and btc interval gain](https://github.com/strangelove-ventures/sommelier/commit/29f2866a7b97428ecd77e1b0c745c8b249a0ace6)
- [x] [feat: create actions to get assets interval gain](https://github.com/strangelove-ventures/sommelier/commit/b4c003e2694b317a44dc97cae7a1dd4814738522)
- [x] [feat: create utils to get gain pct data](https://github.com/strangelove-ventures/sommelier/commit/13bebdec78bf2ab0f08a6e56b94fe6ea3710f8f2)
- [x] [feat: add get today and previous month](https://github.com/strangelove-ventures/sommelier/commit/56d936fc39f0cd7a541b4c6b17e0b600d418f73e)
- [x] [feat: create query to get single cellar value](https://github.com/strangelove-ventures/sommelier/commit/32c5b0ed81f2ccabc78d7746dd22eb22255237c9) 
- [x] [feat: getPreviousMonth calculation](https://github.com/strangelove-ventures/sommelier/commit/8f1c7ceaa925d148a35a0731a7df8f59ca4dc225) 
- [x] [feat: add intervalGainPct in about cellar](https://github.com/strangelove-ventures/sommelier/commit/e34c2a8d2e801b27f03df4cdcdad403fd96fad2e)
- [x] [feat: add intervalGainPct in page cellar](https://github.com/strangelove-ventures/sommelier/commit/ec278038dc25c4a05eb9ccbd8296926d23eeb2d7)
- [x] [feat: add intervalGainPct in hero section](https://github.com/strangelove-ventures/sommelier/commit/e82bca6ad3fb22c5616d85c5c16e1a399dcc825f)

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/43783037/200677940-e137b4ee-28f8-499d-966b-0b1c5a64535f.png)
![image](https://user-images.githubusercontent.com/43783037/200677995-2d86375a-ef46-4bb1-8702-73bbeac8e884.png)
![image](https://user-images.githubusercontent.com/43783037/200678024-33c4e511-51f2-43bf-8eab-55638c168080.png)

## Links
https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=2195:101054

2022-11-08 21:39 UTC, codingki requested changes

2022-11-08 21:39 UTC, codingki commented on src/components/CellarStatsAutomated.tsx
> +            analytics.track("user.tooltip-opened-daily-change")
tooltip-opened-monthly-change

2022-11-08 21:39 UTC, codingki commented on src/data/hooks/useIntervalGainPct.ts
> +      previousMonthDatas,
previousMonthDatas[0].shareValue

2022-11-08 21:41 UTC, codingki commented on src/utils/calculateTime.ts
> +    dayInSecs * 3
this is weird, I don't know about the calculation, but by reading this seems make no sense it's a previous month cc @xanderjl @sandbochs

2022-11-08 22:07 UTC, xanderjl requested changes
All of the logic is very close! Just a few best practice things I'd change and I'd say this is good to go. Great work @joshuanatanielnm 😄

2022-11-08 22:55 UTC, joshuanatanielnm commented on src/components/HeroStrategy/hero-right.tsx
> +        <VStack w="30%">
Thanks Xan that solve the issue

2022-11-08 23:22 UTC, joshuanatanielnm commented on src/components/PercentageText.tsx
> +
Thanks Xan 🚀

2022-11-09 16:33 UTC, codingki approved these changes

2022-11-09 18:53 UTC, merged